### ISSUE TITLE
Region.php 文件语法异常了

### ISSUE THREAD

**Issue by zhanghuid** [huaweicloud/huaweicloud-sdk-php-v3#5]
### 如下代码的 53 行
https://github.com/huaweicloud/huaweicloud-sdk-php-v3/blob/master/Core/src/Region/Region.php

`php` 是没有 `$this.xxx` 这种语法的

**Comment by hanyongchao007** [comment]
下个版本会修复此问题

**Comment by zhanghuid** [comment]
还有一个问题，为啥不支持 eps 相关的功能呢？我看 go 都支持上了

**Comment by hanyongchao007** [comment]
不支持请联系下EPS服务支撑人员
